services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: "oracle"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - carbontracker-net
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carbontrackerapi
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
    depends_on:
      - oracle
    networks:
      - carbontracker-net

networks:
  carbontracker-net:
    driver: bridge

volumes:
  oracle-data:
