name: Deploy to Cloud Run
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build and Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: carbontrackerapi
          region: southamerica-east1
          source: .
